#version: '3.9'
#services:
#  backend:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - postgres
#
#
#  postgres:
#    container_name: postgres
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1234
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
